import { Roboto, Fraunces } from 'next/font/google';
import './globals.css';
import { NextUIProvider } from '@nextui-org/react';

const queenFont = Fraunces({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={queenFont.className}>
        <NextUIProvider>{children}</NextUIProvider>
      </body>
    </html>
  );
}
